### ISSUE TITLE
[poll] Editor of choice for Vue project

### ISSUE THREAD

**Issue by egoist** [vue-land/vue-land#1]
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/VSCode)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/VSCode/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/Atom)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/Atom/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/Sublime)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/Sublime/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/IDE)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMEM5Q0TAPJAZP3W5ZRA5TE1/IDE/vote)

**Comment by cristijora** [comment]
IDE = what?
Maybe add Webstorm?

**Comment by egoist** [comment]
@cristijora I think most likely it means Webstorm lol, I can't update existing polls though since it's not allowed [by design](https://github.com/tj/gh-polls).

**Comment by egoist** [comment]
How come I forgot Vim and Emacs?

**Comment by egoist** [comment]
VSCode won here, but indeed I see many people use WebStorm too.
