### ISSUE TITLE
[poll] An anime channel?

### ISSUE THREAD

**Issue by egoist** [vue-land/vue-land#3]
Cuz Vue has an [anime soul](https://github.com/egoist/always-bet-on-vue).

<a href="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMJR82A2AXXXV3SA1ASVETFY/Yes%20please!/vote"><img src="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMJR82A2AXXXV3SA1ASVETFY/Yes%20please!" alt=""></a>
<a href="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMJR82A2AXXXV3SA1ASVETFY/Go%20somewhere%20else%20%3A(/vote"><img src="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMJR82A2AXXXV3SA1ASVETFY/Go%20somewhere%20else%20%3A(" alt=""></a>

**Comment by gustojs** [comment]
Absolutely! #anime channel is a channel Vue Land deserves, even if it's not the one it needs.
