### ISSUE TITLE
Do you want Vue to provide class based API by default?

### ISSUE THREAD

**Issue by egoist** [vue-land/vue-land#6]
Related: https://github.com/vuejs/vue-class-component/issues/223

[![](https://api.gh-polls.com/poll/01C7Z7EAQ47ANWGJ2FJN33PCBZ/Yes)](https://api.gh-polls.com/poll/01C7Z7EAQ47ANWGJ2FJN33PCBZ/Yes/vote)
[![](https://api.gh-polls.com/poll/01C7Z7EAQ47ANWGJ2FJN33PCBZ/No)](https://api.gh-polls.com/poll/01C7Z7EAQ47ANWGJ2FJN33PCBZ/No/vote)

**Comment by kevinmarrec** [comment]
@egoist Can be closed I guess - https://github.com/vuejs/rfcs/pull/17

**Comment by egoist** [comment]
@kevinmarrec Yes, thanks 😄
