### ISSUE TITLE
Discord invite link has expired

### ISSUE THREAD

**Issue by SageStarCodes** [vue-land/vue-land#7]
https://discordapp.com/invite/HBherRA is no longer valid - this invite link is used on both chat.vuejs.org and on the https://vue-land.js.org/

Screenshot: http://prntscr.com/j6jyxj

**Comment by egoist** [comment]
weird it's still valid forme, actually it's set to never expire

**Comment by SageStarCodes** [comment]
Solved... I copied the link into Discord into the "Join a server" dialog and it worked... Might be a Discord bug then :-/
